baseurl = "https://tobiasraabe.github.io/"
theme = "cocoa-eh-hugo-theme"
enableRobotsTXT = true
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "publish"
author = "Tobias Raabe"
title = "Tobias Raabe"
pluralizelisttitles = false

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  taxonomies = "taxonomies"

[permalinks]
    blog = "blog/:slug/"

[params]
    dateform = "Jan 2, 2006"
    dateformfull = "Mon Jan 2 2006 15:04:05 MST"
    description = "Economics, Data Analysis, etc."
    copyright = "Copyright © 2017 Tobias Raabe"
    copyrightUrl = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
    logofile = "images/favicon.png"
    faviconfile = "images/favicon.png"
    highlightjs = true
    progressively = true
    share = false
    latestpostcount = 10
    github = "tobiasraabe"
    email = "tobiasraabe@uni-bonn.de"
    linkedin = "tobias-raabe"
    usesmallsummarycard = false
    posts_navigation = true
    small_banner_logo = false
    extracssfiles = ["css/style.css"]

[params.colors]
    identifier = "#527fc1f"
    identifier_dark = "#1a3152"
    trivial = "#6a7a8b"
    foreground = "#181d2a"
    background = "#f9f9f9"
    background_dark = "#282a36"
    code = "#87a5d2"
    type = "#97d28b"
    special = "#ffcb8d"
    value = "#96c2d7"
    statement = "#ff8e91"
