name: hp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.3
  - pip=18.1
  - numba
  - scipy
  - pip:
    - beautifulsoup4==4.7.1
    - ghp-import==0.5.5
    - jupyter==1.0.0
    - markdown==3.1
    - pelican==4.0.1
    - pybtex==0.22.2
    - jupyterlab==0.35.4
    - matplotlib