name: hp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.2
  - pip=18.1
  - pip:
    - beautifulsoup4==4.6.3
    - ghp-import==0.5.5
    - jupyter==1.0.0
    - markdown==3.0.1
    - pelican==3.7.1
    - pybtex==0.21