name: hp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numba
  - scipy
  - pre-commit
  - beautifulsoup4>=4.7.1
  - ghp-import>=0.5.5
  - jupyter>=1.0.0
  - markdown>=3.1.1
  - pelican>=4.1,<4.5
  - pybtex>=0.22.2
  - jupyterlab>=1.0.0
  - matplotlib>=3.1.0
  - nbconvert=5
  - parso=0.8

  - pip:
    - pelican-jupyter
    - pelican-render-math
    - git+https://github.com/StevenMaude/pelican-i18n_subsites
