name: hp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numba
  - scipy
  - beautifulsoup4>=4.7.1
  - ghp-import>=0.5.5
  - jupyter>=1.0.0
  - markdown>=3.1.1
  - pelican>=4.1
  - pybtex>=0.22.2
  - jupyterlab>=1.0.0
  - matplotlib>=3.1.0
