channels:
  - defaults
dependencies:
  - python=3.6
  - pip=18.0
  - numpy=1.15.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - pip:
    - matplotlib==2.2.2
    - pandas==0.23.4
    - requests==2.19.1
    - seaborn==0.9.0
    - tqdm==4.25.0
